spring:
  port: 8085

  datasource:
    url: jdbc:postgresql://localhost:5432/chatMicro
    username: postgres
    password: tomita24
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



