version: '3.9'

services:
  java_app:
    container_name: java_app
    image: usermicro/java_app:1.0.0
    build: ./UserMicro
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/userzz
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db
      
  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userzz
    volumes:
      - pgdata:/var/lib/postgresql/data

  java_app2:
    container_name: java_app2
    image: devicemicro/java_app2:1.0.0
    build: ./DeviceMicro
    ports:
      - 8089:8089
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db2:5432/devicezz
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db2

  java_db2:
    container_name: java_db2
    image: postgres:12
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devicezz
    volumes:
      - pgdata2:/var/lib/postgresql/data
   
  react_app:
    container_name: react_app
    build: ./fronthatz
    ports:
     - "5173:5173"


volumes:
  pgdata: {}
  pgdata2: {}